spring:
  application:
    name: mingyu-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 172.30.1.83:8848

server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include: "*"